export type ExerciseCategory =
  | "Knee"
  | "Hip"
  | "Shoulder"
  | "Spine & core"
  | "Ankle & foot"
  | "Balance";

export type Exercise = {
  id: string;
  name: string;
  category: ExerciseCategory;
  level: "Starter" | "Progressing" | "Advanced";
  equipment: string;
  position: string;
  focus: string;
  cue: string;
  automatedScoring: boolean;
};

export const EXERCISES: Exercise[] = [
  {
    id: "chair-sit-to-stand",
    name: "Chair sit-to-stand",
    category: "Knee",
    level: "Starter",
    equipment: "Stable chair",
    position: "Side view",
    focus: "Knee range and trunk control",
    cue: "Keep your chest tall and press evenly through both feet.",
    automatedScoring: true,
  },
  {
    id: "heel-slide",
    name: "Supine heel slide",
    category: "Knee",
    level: "Starter",
    equipment: "Mat or bed",
    position: "Side view",
    focus: "Gentle knee flexion",
    cue: "Slide the heel slowly without forcing the range.",
    automatedScoring: false,
  },
  {
    id: "seated-knee-extension",
    name: "Seated knee extension",
    category: "Knee",
    level: "Starter",
    equipment: "Chair",
    position: "Side view",
    focus: "Quadriceps control",
    cue: "Straighten the knee without lifting the thigh.",
    automatedScoring: false,
  },
  {
    id: "straight-leg-raise",
    name: "Straight-leg raise",
    category: "Knee",
    level: "Progressing",
    equipment: "Mat",
    position: "Side view",
    focus: "Quadriceps and hip flexor control",
    cue: "Keep the knee straight and lift only to the prescribed height.",
    automatedScoring: false,
  },
  {
    id: "mini-squat",
    name: "Supported mini squat",
    category: "Knee",
    level: "Progressing",
    equipment: "Counter or rail",
    position: "Side view",
    focus: "Controlled weight bearing",
    cue: "Hips back, knees aligned with the second toe.",
    automatedScoring: false,
  },
  {
    id: "step-up",
    name: "Low step-up",
    category: "Knee",
    level: "Advanced",
    equipment: "Low stable step",
    position: "Front or side view",
    focus: "Single-leg control",
    cue: "Keep the pelvis level and lower with control.",
    automatedScoring: false,
  },
  {
    id: "glute-bridge",
    name: "Glute bridge",
    category: "Hip",
    level: "Starter",
    equipment: "Mat",
    position: "Side view",
    focus: "Hip extension strength",
    cue: "Lift through the hips without arching the lower back.",
    automatedScoring: false,
  },
  {
    id: "clamshell",
    name: "Side-lying clamshell",
    category: "Hip",
    level: "Starter",
    equipment: "Mat",
    position: "Front oblique view",
    focus: "Hip rotator strength",
    cue: "Keep the pelvis stacked as the top knee opens.",
    automatedScoring: false,
  },
  {
    id: "hip-abduction",
    name: "Side-lying hip abduction",
    category: "Hip",
    level: "Progressing",
    equipment: "Mat",
    position: "Front view",
    focus: "Gluteus medius strength",
    cue: "Lead with the heel and keep the toes facing forward.",
    automatedScoring: false,
  },
  {
    id: "standing-hip-extension",
    name: "Standing hip extension",
    category: "Hip",
    level: "Progressing",
    equipment: "Counter or rail",
    position: "Side view",
    focus: "Hip extension without trunk compensation",
    cue: "Move the leg back without leaning the trunk.",
    automatedScoring: false,
  },
  {
    id: "pendulum",
    name: "Shoulder pendulum",
    category: "Shoulder",
    level: "Starter",
    equipment: "Table support",
    position: "Front oblique view",
    focus: "Gentle shoulder mobility",
    cue: "Let the arm stay relaxed while the body creates the motion.",
    automatedScoring: false,
  },
  {
    id: "wall-slide",
    name: "Shoulder wall slide",
    category: "Shoulder",
    level: "Starter",
    equipment: "Wall",
    position: "Side view",
    focus: "Assisted elevation",
    cue: "Slide only through the comfortable prescribed range.",
    automatedScoring: false,
  },
  {
    id: "shoulder-abduction",
    name: "Standing shoulder abduction",
    category: "Shoulder",
    level: "Progressing",
    equipment: "None",
    position: "Front view",
    focus: "Shoulder elevation control",
    cue: "Keep the shoulder relaxed as the arm moves outward.",
    automatedScoring: false,
  },
  {
    id: "external-rotation",
    name: "Band external rotation",
    category: "Shoulder",
    level: "Progressing",
    equipment: "Light resistance band",
    position: "Front view",
    focus: "Rotator cuff strength",
    cue: "Keep the elbow tucked against the side.",
    automatedScoring: false,
  },
  {
    id: "pelvic-tilt",
    name: "Supine pelvic tilt",
    category: "Spine & core",
    level: "Starter",
    equipment: "Mat",
    position: "Side view",
    focus: "Lumbopelvic control",
    cue: "Gently flatten the lower back without holding your breath.",
    automatedScoring: false,
  },
  {
    id: "cat-cow",
    name: "Cat-cow mobility",
    category: "Spine & core",
    level: "Starter",
    equipment: "Mat",
    position: "Side view",
    focus: "Spinal mobility",
    cue: "Move slowly and distribute the curve through the whole spine.",
    automatedScoring: false,
  },
  {
    id: "bird-dog",
    name: "Bird dog",
    category: "Spine & core",
    level: "Progressing",
    equipment: "Mat",
    position: "Side view",
    focus: "Trunk stability",
    cue: "Keep the pelvis level while reaching long.",
    automatedScoring: false,
  },
  {
    id: "prone-press-up",
    name: "Prone press-up",
    category: "Spine & core",
    level: "Progressing",
    equipment: "Mat",
    position: "Side view",
    focus: "Lumbar extension mobility",
    cue: "Relax the hips and stop if symptoms spread or intensify.",
    automatedScoring: false,
  },
  {
    id: "ankle-pumps",
    name: "Ankle pumps",
    category: "Ankle & foot",
    level: "Starter",
    equipment: "None",
    position: "Side view",
    focus: "Ankle mobility and circulation",
    cue: "Move the ankle up and down without moving the whole leg.",
    automatedScoring: false,
  },
  {
    id: "calf-raise",
    name: "Supported calf raise",
    category: "Ankle & foot",
    level: "Progressing",
    equipment: "Counter or rail",
    position: "Side view",
    focus: "Plantar-flexor strength",
    cue: "Rise straight up and lower slowly.",
    automatedScoring: false,
  },
  {
    id: "ankle-inversion-eversion",
    name: "Band inversion / eversion",
    category: "Ankle & foot",
    level: "Progressing",
    equipment: "Light resistance band",
    position: "Front view",
    focus: "Ankle control",
    cue: "Move from the ankle while keeping the knee still.",
    automatedScoring: false,
  },
  {
    id: "tandem-stance",
    name: "Tandem stance",
    category: "Balance",
    level: "Starter",
    equipment: "Counter nearby",
    position: "Front view",
    focus: "Narrow-base balance",
    cue: "Stand near support and keep your gaze on a fixed point.",
    automatedScoring: false,
  },
  {
    id: "single-leg-balance",
    name: "Supported single-leg balance",
    category: "Balance",
    level: "Progressing",
    equipment: "Counter nearby",
    position: "Front view",
    focus: "Single-leg stability",
    cue: "Use fingertip support and keep the pelvis level.",
    automatedScoring: false,
  },
  {
    id: "lateral-step",
    name: "Lateral stepping",
    category: "Balance",
    level: "Advanced",
    equipment: "Clear walkway",
    position: "Front view",
    focus: "Dynamic balance",
    cue: "Stay tall and place each foot with control.",
    automatedScoring: false,
  },
];

export const EXERCISE_CATEGORIES = [
  "All",
  "Knee",
  "Hip",
  "Shoulder",
  "Spine & core",
  "Ankle & foot",
  "Balance",
] as const;
